export const TOGGLE_HEADING_FORM = 'TOGGLE_HEADING_FORM';
export const TOGGLE_TIMESPAN_FORM = 'TOGGLE_TIMESPAN_FORM';
export const ADD_HEADING = 'ADD_HEADING';
export const EDIT_HEADING = 'EDIT_HEADING';
export const ADD_TIME_SPAN = 'ADD_TIME_SPAN';
export const EDIT_TIME_SPAN = 'EDIT_TIME_SPAN';
export const BUILD_SM_UI = 'BUILD_SM_UI';

export const DELETE_ITEM = 'DELETE_ITEM';

export const ADD_DROP_TARGETS = 'ADD_DROP_TARGETS';
export const REMOVE_DROP_TARGETS = 'REMOVE_DROP_TARGETS';
export const SET_ACTIVE_DRAG_SOURCE = "SET_ACTIVE_DRAG_SOURCE";
export const REMOVE_ACTIVE_DRAG_SOURCES = "REMOVE_ACTIVE_DRAG_SOURCES";
export const HANDLE_LIST_ITEM_DROP = "HANDLE_LIST_ITEM_DROP";

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SAVE_MODAL_RECORD = 'SAVE_MODAL_RECORD';

